#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/parser.h"
#include "../include/codegen.h"
#include "../include/vm.h"
#include "../include/ir.h"

int main(int argc, char **argv) {
    if (argc < 2) {
        printf("Usage: %s <c_source>\n", argv[0]);
        return 1;
    }

    // TODO: Read file instead of hardcode
    const char *source = "1 + 2 * 3";

    printf("Compiling: %s\n", source);

    tokenize(source);
    parse();
    codegen();

    printf("Generated %zu bytes of bytecode\n", bc_idx);

    // Run the generated bytecode on the ternary VM
    vm_run(bytecode, bc_idx);

    return 0;
}
